#!/usr/bin/env python3
"""Render a LaTeX-oriented tracker table from progress/tasks/*.md."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TASKS = ROOT / "progress" / "tasks"


def parse_task(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    owner = status = notes = ""
    title = path.stem
    m = re.search(r"^#\s+(T-\d+)\s+-\s+(.+)$", text, re.M)
    if m:
        title = f"{m.group(1)} {m.group(2).strip()}"
    om = re.search(r"Owner:\s*([^|]+)", text)
    if om:
        owner = om.group(1).strip()
    sm = re.search(r"Status:\s*([^|]+)", text)
    if sm:
        status = sm.group(1).strip()
    nm = re.search(r"Notes:\s*(.+)$", text, re.M)
    if nm:
        notes = nm.group(1).strip()
    return {"id": path.stem, "title": title, "owner": owner, "status": status, "notes": notes}


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate tracker rows from progress/tasks/*.md (stdout)."
    )
    parser.parse_args()
    rows = [parse_task(p) for p in sorted(TASKS.glob("T-*.md"))]
    print("% Generated by scripts/gen_tracker.py — do not hand-edit tracker tables")
    for r in rows:
        print(f"{r['id']} & {r['title']} & {r['owner']} & {r['status']} & {r['notes']} \\\\")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
