#!/usr/bin/env python3
"""Generate DIRECTORY.md — never hand-edit that file (rule R6)."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TOP_FOLDERS = [
    (".github/workflows/", "[JOINT] CI: ci-push.yml, merge-gate.yml"),
    ("src/cim/", "[JOINT] Python package cim (src-layout)"),
    ("src/cim/common/", "[JOINT border] schema [F], store/chain [H], config [JOINT]"),
    ("src/cim/mcp/", "[H] MCP-side sole territory"),
    ("src/cim/skills/", "[F] Skills-side sole territory"),
    ("src/cim/correlation/", "[H leads] correlation engine"),
    ("src/cim/scanners/", "mcp/ [H], skills/ [F]"),
    ("src/cim/attestation/", "hostagent/ [H], verifier/ [F]"),
    ("src/cim/adjudicator/", "[H leads] LLM adjudication"),
    ("src/cim/dashboard/", "[H leads] review UI"),
    ("scripts/", "[JOINT] bootstrap, check-env, generators"),
    ("tests/", "mcp/ [H], skills/ [F], common|sys [JOINT]"),
    ("corpora/", "mcp/ [H], skills/ [F]"),
    ("history/", "[JOINT] audit log entries + weekly digests"),
    ("progress/", "[JOINT] single source of truth for status"),
    ("docs/", "[JOINT] plan PDF, ADRs, runbooks"),
    ("logs/", "[JOINT] GITIGNORED runtime output"),
    ("scratch/", "[JOINT] GITIGNORED experiments"),
]


def render() -> str:
    lines = [
        "# DIRECTORY",
        "",
        "_Generated by `scripts/gen_directory.py`. Do not hand-edit (rule R6)._",
        "",
        "| Path | Owner / note |",
        "|------|--------------|",
    ]
    for path, note in TOP_FOLDERS:
        lines.append(f"| `{path}` | {note} |")
    lines.append("")
    lines.append("Territory map details: plan PDF §4.2; onboarding: CONTEXT.md.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate DIRECTORY.md from the ownership map.")
    parser.add_argument("--help-text", action="store_true", help=argparse.SUPPRESS)
    parser.parse_args()
    out = ROOT / "DIRECTORY.md"
    out.write_text(render(), encoding="utf-8")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
